import './global.css';
import { JustaNameProviderWrapper } from './providers/justaname';
import { ReactQueryProvider } from './providers/react-query';

export const metadata = {
  title: 'Welcome to keys-jaw-id',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <JustaNameProviderWrapper>
          <body>{children}</body>
        </JustaNameProviderWrapper>
      </ReactQueryProvider>
    </html>
  )
}
